### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by wubadubdub** [AbenezerMamo/crypto-signal#15]
First of all thanks, this is a cool application, if only i could get it to work reliably! 

every time i run the app i get different errors, is there something i am doing wrong?

Thanks,

```

BTC-ETH:        Breakout: None  RSI: 18.419935880075528
BTC-OMG:        Breakout: None  RSI: 21.50681271707181
BTC-GNT:        Breakout: None  RSI: 21.246537396121866
BTC-CVC:        Breakout: None  RSI: 46.46287403029179
Traceback (most recent call last):
  File "app.py", line 145, in <module>
    get_signal()
  File "app.py", line 140, in get_signal
    breakout = findBreakout(coin_pair=i, period=5, unit="fiveMin")
  File "app.py", line 132, in findBreakout
    historical_data = my_bittrex.getHistoricalData(coin_pair, period, unit)
  File "C:\PROJECTS\crypto-signal-master\bittrex.py", line 134, in getHistoricalData
    headers={"apisign": hmac.new(self.api_secret.encode(), request_url.encode(), hashlib.sha512).hexdigest()}
  File "C:\Program Files\Anaconda3\lib\site-packages\requests\models.py", line 885, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\Program Files\Anaconda3\lib\json\__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "C:\Program Files\Anaconda3\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Program Files\Anaconda3\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

second time..
```

BTC-ETH:        Breakout: None  RSI: 53.86451742552738
BTC-OMG:        Breakout: None  RSI: 21.589990345141373
Traceback (most recent call last):
  File "app.py", line 145, in <module>
    get_signal()
  File "app.py", line 140, in get_signal
    breakout = findBreakout(coin_pair=i, period=5, unit="fiveMin")
  File "app.py", line 132, in findBreakout
    historical_data = my_bittrex.getHistoricalData(coin_pair, period, unit)
  File "C:\PROJECTS\crypto-signal-master\bittrex.py", line 137, in getHistoricalData
    return historicalData['result'][-period:]
TypeError: 'NoneType' object is not subscriptable
```

third time...

```
Traceback (most recent call last):
  File "app.py", line 145, in <module>
    get_signal()
  File "app.py", line 141, in get_signal
    rsi = calculateRSI(coin_pair=i, period=14, unit="thirtyMin")
  File "app.py", line 77, in calculateRSI
    relative_strength = (average_gain / average_loss)
ZeroDivisionError: float division by zero
```

**Comment by AbenezerMamo** [comment]
@wubadubdub Can you share your script's settings after the "if __name__ == "__main__":" towards the bottom?

Also, try the latest changes and see if you get the same errors. We'll figure it out!

**Comment by tsluder8** [comment]
I receive the same errors daily, until I set up a cronjob to restart the script throughout the day.  Most common traceback is below:

`  File "/usr/local/lib/python2.7/dist-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded`

**Comment by brashlin** [comment]
Firstly a massive thanks to you AbenezerMamo. Thanks for your time and for sharing this excellent bit of code. ;)

I had similar problems and my solution might not be that clean but it keeps the script running. 
This takes care of the fist problem mentioned - 

 for i in coin_pairs:
                try:
                    breakout = findBreakout(coin_pair=i, period=5, unit="fiveMin")
                except  requests.exceptions.RequestException as e:
                    print e

I also ran the app.py file in a while loop as follows - 

while True:
        try:
                execfile("app.py")
                
        except  Exception as e:
                print " timeout"

This took care of internet dropouts.
The script has now been running for weeks without any intervention. 

Good luck

**Comment by bitcoinrate** [comment]
the app runs and shows RSI and breakout message. Does it do other stuff? what are the commands to run? Thx
