### ISSUE TITLE
script keeps crashing, how to fix this error?

### ISSUE THREAD

**Issue by devalias** [AbenezerMamo/crypto-signal#17]
This is the message.

Traceback (most recent call last):
  File "/home/osboxes/crypto-signal/app.py", line 232, in <module>
    get_signal()
  File "/home/osboxes/crypto-signal/app.py", line 183, in get_signal
    breakout = findBreakout(coin_pair=i, period=5, unit="fiveMin")
  File "/home/osboxes/crypto-signal/app.py", line 157, in findBreakout
    rsi = calculateRSI(coin_pair=i, period=14, unit="thirtyMin")
  File "/home/osboxes/crypto-signal/app.py", line 63, in calculateRSI
    closing_prices = getClosingPrices(coin_pair, period * 3, unit)
  File "/home/osboxes/crypto-signal/app.py", line 31, in getClosingPrices
    historical_data = my_bittrex.getHistoricalData(coin_pair, period, unit)
  File "/home/osboxes/crypto-signal/bittrex.py", line 137, in getHistoricalData
    return historicalData['result'][-period:]
TypeError: 'NoneType' object has no attribute '__getitem__'

Any suggestions?  Nice script!

**Comment by devalias** [comment]
getting this also:

Traceback (most recent call last):
  File "crypto_signals.py", line 235, in <module>
    get_signal()
  File "crypto_signals.py", line 187, in get_signal
    rsi = calculateRSI(coin_pair=i, period=14, unit="thirtyMin")
  File "crypto_signals.py", line 102, in calculateRSI
    rs = newAvgGain / newAvgLoss;
ZeroDivisionError: integer division or modulo by zero

**Comment by GiorgosK** [comment]
get the same error 

> Traceback (most recent call last):
>   File "app.py", line 173, in <module>
>     get_signal()
>   File "app.py", line 169, in get_signal
>     rsi = calculateRSI(coin_pair=i, period=14, unit="thirtyMin")
>   File "app.py", line 66, in calculateRSI
>     closing_prices = getClosingPrices(coin_pair, period * 3, unit)
>   File "app.py", line 34, in getClosingPrices
>     historical_data = my_bittrex.getHistoricalData(coin_pair, period, unit)
>   File "/home/signal/bittrex.py", line 137, in getHistoricalData
>     return historicalData['result'][-period:]
> TypeError: 'NoneType' object has no attribute '__getitem__'
>

**Comment by Andreilys** [comment]
The reason it says "NoneType" is that bittrex is returning a None type when you use the getHistoricalData() method

I had a similar issue, mine had to do with instantiating the coin pairs in app.py and .env, are your coin pairs comma separated in the format that Bittrex has? (i.e. 'BTC-xxx')

Another issue could be with how you instantiate bittrex (incorrect keys?). Let me know if this helps!
