### ISSUE TITLE
socket.timeout: The read operation timed out

### ISSUE THREAD

**Issue by Danielson187** [AbenezerMamo/crypto-signal#45]
Hi guys,

I'm getting alot of  time-out and then de app stops:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/local/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 294, in recv_into
    raise timeout('The read operation timed out')
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 389, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
    raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='bittrex.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 342, in fetch_requests
    proxies=self.proxies
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 521, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='bittrex.com', port=443): Read timed out. (read timeout=10)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app.py", line 83, in <module>
    main()
  File "app.py", line 61, in main
    get_signal(coin_pairs, strategy_analyzer, notifier)
  File "app.py", line 68, in get_signal
    ichimoku_span_a, ichimoku_span_b = strategy_analyzer.analyze_ichimoku_cloud(coin_pair)
  File "/app/analysis.py", line 56, in analyze_ichimoku_cloud
    time_unit='1d'
  File "/app/exchange.py", line 33, in get_historical_data
    limit=period_count))
  File "/usr/local/lib/python3.6/site-packages/ccxt/bittrex.py", line 389, in fetch_ohlcv
    response = self.v2GetMarketGetTicks(self.extend(request, params))
  File "/usr/local/lib/python3.6/site-packages/ccxt/bittrex.py", line 618, in request
    response = self.fetch2(path, api, method, params, headers, body)
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 290, in fetch2
    return self.fetch_requests(request['url'], request['method'], request['headers'], request['body'])
  File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 348, in fetch_requests
    raise RequestTimeout(' '.join([self.id, method, url, 'request timeout']))
ccxt.base.errors.RequestTimeout: bittrex GET https://bittrex.com/api/v2.0/pub/market/GetTicks?tickInterval=day&marketName=BTC-STEEM request timeout

**Comment by shads2** [comment]
The cascade of errors will just be a result of us not doing a very good job of error handling yet.

The actual error you are experiencing though is that for whatever reason your computer is unable to make a network connection over HTTPS to bittrex.

If you were to run `telnet bittrex.com 443` or `curl https://bittrex.com/api/v2.0/pub/market/GetTicks?tickInterval=day&marketName=BTC-STEEM` you would likely get the same error. You will need to work out why traffic is being blocked when trying to reach the website.

**Comment by Danielson187** [comment]
curl seems to be working, is it possible to set a custom time-out value?

**Comment by shads2** [comment]
There's a patch coming to master soon that will handle timeouts for coin look ups more gracefully... I will update this issue once it is merged :)

**Comment by shads2** [comment]
While not the end to the work I want to do for safer error handling, we are now at least catching this exception and handling it.
