### ISSUE TITLE
Mail notifier not always working.

### ISSUE THREAD

**Issue by Danielson187** [AbenezerMamo/crypto-signal#46]
Traceback (most recent call last):
  File "app.py", line 83, in <module>
    main()
  File "app.py", line 61, in main
    get_signal(coin_pairs, strategy_analyzer, notifier)
  File "app.py", line 70, in get_signal
    notifier.notify_all(message="{} is breaking out!".format(coin_pair))
  File "/app/notification.py", line 53, in notify_all
    self.notify_gmail(message)
  File "/app/notification.py", line 75, in notify_gmail
    self.gmail_client.notify(message)
  File "/app/notifiers/gmail.py", line 31, in notify
    self.smtp_handler.starttls()
  File "/usr/local/lib/python3.6/smtplib.py", line 749, in starttls
    self.ehlo_or_helo_if_needed()
  File "/usr/local/lib/python3.6/smtplib.py", line 600, in ehlo_or_helo_if_needed
    if not (200 <= self.ehlo()[0] <= 299):
  File "/usr/local/lib/python3.6/smtplib.py", line 440, in ehlo
    self.putcmd(self.ehlo_msg, name or self.local_hostname)
  File "/usr/local/lib/python3.6/smtplib.py", line 367, in putcmd
    self.send(str)
  File "/usr/local/lib/python3.6/smtplib.py", line 359, in send
    raise SMTPServerDisconnected('please run connect() first')
smtplib.SMTPServerDisconnected: please run connect() first

**Comment by shads2** [comment]
Right now this functionality hasn't had very much testing, though I suspect this problem may be related to your connectivity problems in https://github.com/AbenezerMamo/crypto-signal/issues/45

**Comment by shads2** [comment]
I am going to close this for now.
