### ISSUE TITLE
bittrex does not have market symbol 

### ISSUE THREAD

**Issue by ahmetoz** [AbenezerMamo/crypto-signal#48]
Hi,

I am getting this error: What should I do ?

Details:
``` yml
#Make sure that this matches bittrex format of BTC-XXX
MARKET_PAIRS=BTC-LTC, BTC-ETH
````

``` shell
Successfully built f3e1d05ed345
Successfully tagged cryptosignal_app:latest
Creating cryptosignal_app_1 ...
Creating cryptosignal_app_1 ... done
Attaching to cryptosignal_app_1
app_1  | Traceback (most recent call last):
app_1  |   File "app.py", line 83, in <module>
app_1  |     main()
app_1  |   File "app.py", line 61, in main
app_1  |     get_signal(coin_pairs, strategy_analyzer, notifier)
app_1  |   File "app.py", line 65, in get_signal
app_1  |     rsi_value = strategy_analyzer.analyze_rsi(coin_pair)
app_1  |   File "/app/analysis.py", line 35, in analyze_rsi
app_1  |     time_unit=time_unit
app_1  |   File "/app/exchange.py", line 33, in get_historical_data
app_1  |     limit=period_count))
app_1  |   File "/usr/local/lib/python3.6/site-packages/ccxt/bittrex.py", line 384, in fetch_ohlcv
app_1  |     market = self.market(symbol)
app_1  |   File "/usr/local/lib/python3.6/site-packages/ccxt/base/exchange.py", line 1011, in market
app_1  |     raise ExchangeError(self.id + ' does not have market symbol ' + str(symbol))
app_1  | ccxt.base.errors.ExchangeError: bittrex does not have market symbol BTC-LTC
```

**Comment by ahmetoz** [comment]
It seems, cctx wants LTC/ETH format, but the .env file has a comment ( #Make sure that this matches bittrex format of BTC-XXX).

**Comment by coinmining** [comment]
@ahmetoz here is a gist of all the Bitrex symbols format as cctx sees them

https://gist.github.com/coinmining/95a21ad38f68f2da194052a8b066eca7

**Comment by ahmetoz** [comment]
wow thank you ! maybe i should add this gist's link to this repository 🤔

**Comment by ahmetoz** [comment]
and already added. good 😄
