### ISSUE TITLE
install issues

### ISSUE THREAD

**Issue by Tim9889** [AbenezerMamo/crypto-signal#59]
after  `make build` which gives no errors I try to run the app using 'make run', unfortunately theres no .env folder generated, how can I do this / whats wrong with the install process?

```
docker run -it --rm --env-file .env crypto-signal
docker: open .env: no such file or directory.
```

**Comment by Andreilys** [comment]
Hey @aneesv you'll first need to copy template.env into .env

```
cp template.env .env
#update your credentials in vim
vim .env
```

**Comment by Tim9889** [comment]
Thanks but now I get this:

`docker run -it --rm --env-file .env crypto-signal
Traceback (most recent call last):
  File "app.py", line 13, in <module>
    from analysis import StrategyAnalyzer
  File "/app/analysis.py", line 11, in <module>
    from strategies.bollinger_bands import BollingerBands
  File "/app/strategies/bollinger_bands.py", line 5, in <module>
    from strategy_utils import Utils
ModuleNotFoundError: No module named 'strategy_utils'
make: *** [run] Error 1
`

**Comment by aneesv** [comment]
@Tim9889 I have fixed that issue on #58

**Comment by Andreilys** [comment]
Thanks @aneesv!

**Comment by Tim9889** [comment]
Still no success ...??

```
python3.6 app.py 
Traceback (most recent call last):
  File "app.py", line 43, in <module>
    main()
  File "app.py", line 19, in main
    config = conf.Configuration()
  File "/Users/Thorsten/FREQTRADE/crypto-signal/app/conf.py", line 14, in __init__
    config = json.load(open('default-config.json'))
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python3/3.6.4_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 4 column 22 (char 63)
```

**Comment by aneesv** [comment]
@Tim9889 You have an error on your `default-config.json`, You can use https://jsonlint.com/ to validate json
