### ISSUE TITLE
Doesn't execute

### ISSUE THREAD

**Issue by c931812** [AbenezerMamo/crypto-signal#7]
python app.py

Traceback (most recent call last):
  File "app.py", line 9, in <module>
    secrets = json.load(secrets_file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Expecting property name: line 4 column 1 (char 117)

Could you please advise, thnx

**Comment by tsluder8** [comment]
Did you "Add a secrets.json file to the root directory of your project."?

**Comment by c931812** [comment]
I did it, my file looks like this

{
    "bittrex_key" : "BITTREX_API_KEY",
    "bittrex_secret" : "BITTREX_SECRET",
}

**Comment by zemelax** [comment]
I understand correctly, in order to run it, you need to create a text file with secrets.json and add it to the folder with the bot? I'm sorry, novice.

**Comment by zemelax** [comment]
this is my problem

**Comment by AbenezerMamo** [comment]
The problem is at the top of the call stack. Your json file doesn't have the right API keys plugged in. Like the suggestion above, you need to set the following:

{
"bittrex_key" : "BITTREX_API_KEY",
"bittrex_secret" : "BITTREX_SECRET",
}

**Comment by c931812** [comment]
It does but I just didn't post them on github :)

**Comment by numli** [comment]
Is it because you have a comma at the end of your last KVP (Which you shouldn't have) 
Try:
{
"bittrex_key" : "BITTREX_API_KEY",
"bittrex_secret" : "BITTREX_SECRET"
}

**Comment by c931812** [comment]
```
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    secrets = json.load(secrets_file)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 381, in raw_decode
    obj, end = self.scan_once(s, idx)
ValueError: Invalid control character at: line 2 column 58 (char 59)
```

Now I'm getting this after removing the comma

**Comment by numli** [comment]
Could you paste exactly what you've got now? (without the keys obviously)

**Comment by c931812** [comment]
```
Traceback (most recent call last):
  File "app.py", line 1, in <module>
    from bittrex import Bittrex
  File "/../crypto-signal-master/bittrex.py", line 18, in <module>
    import requests
ImportError: No module named requests
```

**Comment by numli** [comment]
Have you set up your python environment with all the modules stated in the requirements.txt?

**Comment by c931812** [comment]
Yes.

**Comment by numli** [comment]
the error suggests that you have not got the _requests_ module running properly in your environment or it's running under a slightly different name?

**Comment by nuieskater** [comment]
This happen to me

**Comment by nimraMalik** [comment]
where is that secret.json file??

**Comment by AbenezerMamo** [comment]
You'll have to create the secret.json file. The issues you guys are running into are simple, I promise. You just have to make sure all the required modules are downloaded. You should the guide in the main README within this repo for installation
