### ISSUE TITLE
Not working with binance

### ISSUE THREAD

**Issue by Blackcol** [AbenezerMamo/crypto-signal#74]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/ccxt/base/exchange.py", line 345, in fetch_requests
    response.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.binance.com/api/v1/klines?symbol=ETHBTC&interval=1d&limit=500&startTime=1507246156330.2341 << Remove decimals and will work!

**Comment by jrbartola** [comment]
Thanks for the issue! It should be fixed now: ebf7f89
