### ISSUE TITLE
Not providing the integram url fails running the app

### ISSUE THREAD

**Issue by marcofranssen** [AbenezerMamo/crypto-signal#81]
```
$ docker-compose up
Starting cryptosignal_app_1 ... done
Attaching to cryptosignal_app_1
app_1  | Traceback (most recent call last):
app_1  |   File "app.py", line 31, in <module>
app_1  |     main()
app_1  |   File "app.py", line 27, in main
app_1  |     behaviour.run(settings['market_pairs'])
app_1  |   File "/app/behaviours/default.py", line 20, in run
app_1  |     self.test_strategies(market_data)
app_1  |   File "/app/behaviours/default.py", line 67, in test_strategies
app_1  |     message="{} is breaking out!".format(market_pair)
app_1  |   File "/app/notification.py", line 61, in notify_all
app_1  |     self.notify_integram(message)
app_1  |   File "/app/notification.py", line 90, in notify_integram
app_1  |     self.integram_client.notify(message)
app_1  |   File "/app/notifiers/integram_client.py", line 18, in notify
app_1  |     req = urllib.request.Request(self.url)
app_1  |   File "/usr/local/lib/python3.6/urllib/request.py", line 329, in __init__
app_1  |     self.full_url = url
app_1  |   File "/usr/local/lib/python3.6/urllib/request.py", line 355, in full_url
app_1  |     self._parse()
app_1  |   File "/usr/local/lib/python3.6/urllib/request.py", line 384, in _parse
app_1  |     raise ValueError("unknown url type: %r" % self.full_url)
app_1  | ValueError: unknown url type: 'INTEGRAM_URL'
```

FYI I also requested a docker image in the Integram repository so we can use that in our docker-compose setup. https://github.com/requilence/integram/issues/52

Is there any way to run without integram support for now?

**Comment by aneesv** [comment]
@marcofranssen It seems you are using default template for .env file. Remove line containing `INTEGRAM_REQUIRED_URL=INTEGRAM_URL` from .env file

It is recommended to remove all unused variables from .env file

**Comment by shads2** [comment]
No further update on this issue, I am closing it for now.
