### ISSUE TITLE
slack notification

### ISSUE THREAD

**Issue by riveryc** [AbenezerMamo/crypto-signal#83]
Hi, 

after adding slack's key and channel, I got following when starting up the app:
```
Traceback (most recent call last):
  File "app.py", line 32, in <module>
    main()
  File "app.py", line 28, in main
    behaviour.run(settings['market_pairs'])
  File "/app/behaviours/default.py", line 43, in run
    self.__test_strategies(market_data)
  File "/app/behaviours/default.py", line 97, in __test_strategies
    message="{} is breaking out!".format(market_pair)
  File "/app/notification.py", line 79, in notify_all
    self.notify_slack(message)
  File "/app/notification.py", line 93, in notify_slack
    self.slack_client.notify(message)
  File "/app/notifiers/slack_client.py", line 35, in notify
    text=message)
TypeError: api_call() missing 1 required positional argument: 'method'
```

Thanks
River

**Comment by shads2** [comment]
Hi River, there is a PR waiting to be merged that changes the way the slack integration works that fixes this. I'll close those issue once that happens.

**Comment by shads2** [comment]
This should now be resolved.
