### ISSUE TITLE
not able to run server.py

### ISSUE THREAD

**Issue by rohit366** [AbenezerMamo/crypto-signal#88]
I am getting an error on running server.py after the installing everything mentioned in the readme

C:\Users\Rohit.METRO-ROHIT\Desktop\crypto-signal-master\app>python server.py
Traceback (most recent call last):
  File "server.py", line 2, in <module>
    from backtesting.backtest import Backtester
  File "C:\Users\Rohit.METRO-ROHIT\Desktop\crypto-signal-master\app\backtesting\backtest.py", line 11, in <module>
    settings = config.get_settings()
AttributeError: 'Configuration' object has no attribute 'get_settings'

C:\Users\Rohit.METRO-ROHIT\Desktop\crypto-signal-master\app>

**Comment by rohit366** [comment]
was resolved by changing the get_settings to settings = config.settings
