### ISSUE TITLE
gdax division by 0

### ISSUE THREAD

**Issue by ddey94** [AbenezerMamo/crypto-signal#95]
running locally on osx 
simply switched `bittrex` to `gdax` in `default-config.json`

What interval should I use? Default, 600 and 1000 is giving me the following error

 ```
d$ python app.py
Traceback (most recent call last):
  File "app.py", line 38, in <module>
    main()
  File "app.py", line 33, in main
    behaviour.run(settings['market_pairs'])
  File "/Users/d/Desktop/crypto-signal-master/app/behaviours/default.py", line 43, in run
    self.__test_strategies(market_data)
  File "/Users/d/Desktop/crypto-signal-master/app/behaviours/default.py", line 85, in __test_strategies
    self.behaviour_config['breakout']['cold']
  File "/Users/d/Desktop/crypto-signal-master/app/analysis.py", line 125, in analyze_breakout
    breakout_value = breakout_analyzer.get_breakout_value(breakout_historical_data)
  File "/Users/d/Desktop/crypto-signal-master/app/strategies/breakout.py", line 32, in get_breakout_value
    percent_positive_trend = hit / len(historical_data)
ZeroDivisionError: division by zero
```

**Comment by shads2** [comment]
This is an error in the breakout logic, I'll see if I can make sure this is fixed in the next branch

**Comment by jrbartola** [comment]
Done
